#!/usr/bin/python

print "# ==== Autogenerated startup calibration oscillator floorplan ===="
for channel in range(0,2):
    for lut in range(0,31):
        target_slice_x = 31 + 2*channel
        target_slice_y = lut*123//30 + 2
        if lut == 0:
            gen = "g_firstlut"
        else:
            gen = "g_nextlut"
        print \
        "INST " \
        "\"tdc/cmp_tdc/cmp_channelbank/g_multi.cmp_channelbank/g_channels[%d].cmp_channel/cmp_ringosc/g_luts[%d].%s.cmp_LUT\"" \
        " LOC = SLICE_X%dY%d;" \
        % (channel, lut, gen, target_slice_x, target_slice_y)

